name = "garuda-startpage"
pages_build_output_dir = "dist/startpage-v3/browser"
compatibility_date = "2024-10-11"

[placement]
mode = "off"

[env.production]
compatibility_date = "2025-05-05"

[env.production.placement]
mode = "smart"
