import { EnvironmentModel } from './environment.model';

export const environment: EnvironmentModel = {
  production: false,
  availableLanguages: [
    'am',
    'ar',
    'de',
    'en',
    'es',
    'eu',
    'fr',
    'gl',
    'hi',
    'hu',
    'id',
    'it',
    'ja',
    'ko',
    'pl',
    'pt',
    'ru',
    'sl',
    'sv',
    'sw',
    'tr',
    'uz',
    'zh-CN',
  ],
  defaultLanguage: 'en',
  forumUrl: 'http://localhost:4200/proxy-forum',
};
